name: "CI"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: 'macos-latest'

    continue-on-error: true

    strategy:
      fail-fast: true
      matrix:
        php-version:
          - '5.6'
          - '7.0'
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2.3.3

      - run: |
          set -xe

          brew --version
          brew tap shivammathur/php
          brew install php@${{ matrix.php-version }}
          ./phpswitch.sh ${{ matrix.php-version }} -s
          switched=$(php -v | grep -e '^PHP' | cut -d' ' -f2 | cut -d. -f1,2)
          if [ "${{ matrix.php-version }}" != "$switched" ]; then
            echo "Expected ${{ matrix.php-version }} got $switched"
            exit 1
          fi
